import assert from 'node:assert/strict';
import fs from 'node:fs';

const source = fs.readFileSync(new URL('./App.tsx', import.meta.url), 'utf8');

assert.match(source, /import appIconUrl from '..\/..\/tools\/prompt-manager-mac\/Assets\/PromptManager\.svg';/);
assert.match(source, /<img src=\{appIconUrl\}/);
assert.match(source, />Prompt Manager<\/div>/);
assert.doesNotMatch(source, />Prompt 管理器<\/div>/);
assert.match(source, /const \[aiRewriteInput, setAiRewriteInput\] = useState\(''\);/);
assert.match(source, /type AIProviderConfig = \{ model: string; apiKey: string; baseUrl: string \};/);
assert.match(source, /providerConfigs\?: Record<string, AIProviderConfig>;/);
assert.match(source, /const \[providerConfigs, setProviderConfigs\] = useState<Record<string, AIProviderConfig>>/);
assert.match(source, /const currentProviderConfig = providerConfigs\[provider\]/);
assert.match(source, /const configuredProviders = PROVIDERS\.filter/);
assert.match(source, /setProviderConfigs\(prev =>/);
assert.match(source, /configuredProviders\.map/);
assert.doesNotMatch(source, />调用模型</);
assert.match(source, /<select[\s\S]*value=\{activeCallProvider\}/);
assert.doesNotMatch(source, /\{item\.label\} · \{config\.model \|\| item\.placeholder\}/);
assert.match(source, /<option key=\{item\.id\} value=\{item\.id\}>\n\s+\{config\.model \|\| item\.placeholder\}\n\s+<\/option>/);
assert.match(source, /const rewriteTemplateWithAI = async \(\) =>/);
assert.match(source, /chat\/completions/);
assert.match(source, /Prompt 优化大师/);
assert.match(source, /不要在字段值里添加“用户输入：”“选题来源：”/);
assert.match(source, /原始输入材料：\\n\$\{brief\}/);
assert.match(source, /setTemplateValues\(prev => \(\{ \.\.\.prev, \.\.\.nextValues \}\)\)/);
assert.match(source, /const \[rewriteHistory, setRewriteHistory\] = useState<Record<string, string>\[\]>\(\[\]\);/);
assert.match(source, /const \[rewriteHistoryIndex, setRewriteHistoryIndex\] = useState\(-1\);/);
assert.match(source, /const \[selectedCategoryId, setSelectedCategoryId\] = useState\(activeTab\);/);
assert.match(source, /const nextHistory = \[\.\.\.baseHistory, nextValues\];/);
assert.match(source, /setTemplateValues\(prev => \(\{ \.\.\.prev, \.\.\.rewriteHistory\[nextIndex\] \}\)\)/);
assert.match(source, />AI改写</);
assert.match(source, /placeholder="输入几个关键词或几句话，AI 会改写成下面字段"/);
assert.match(source, /top-8 z-\[60\]/);
assert.doesNotMatch(source, /bottom-8 z-\[60\]/);
assert.match(source, /minWidth: 148/);
assert.match(source, /whiteSpace: 'nowrap'/);
assert.match(source, /flexShrink: 0/);
assert.match(source, /aiRewriting\s*\?\s*<span>改写中\.\.\.<\/span>/);
assert.match(source, /<span>AI填入字段<\/span>/);
assert.match(source, /const undoLastCall = \(\) =>/);
assert.match(source, /showToast\('已恢复上一次 AI 改写'\)/);
assert.doesNotMatch(source, /messageHandlers\?\.undoPrompt/);
assert.match(source, /上一次调用/);
assert.match(source, /data-prompt-card-id=\{prompt\.id\}/);
assert.match(source, /onPointerDown=\{\(event\) => handlePromptPointerDown\(event, prompt\.id\)\}/);
assert.match(source, /onPointerMove=\{handlePromptPointerMove\}/);
assert.match(source, /data-no-prompt-drag/);
assert.match(source, /promptDragActive/);
assert.match(source, /promptDragOffset/);
assert.match(source, /document\.body\.style\.userSelect = 'none'/);
assert.match(source, /document\.elementsFromPoint/);
assert.match(source, /translate3d\(\$\{promptDragOffset\.x\}px, \$\{promptDragOffset\.y\}px, 0\) scale\(1\.02\)/);
assert.match(source, /transition: isDraggingPrompt \? 'box-shadow 120ms ease, opacity 120ms ease' : undefined/);
assert.match(source, /willChange: isDraggingPrompt \? 'transform' : undefined/);
assert.match(source, /pointerEvents: isDraggingPrompt \? 'none' : undefined/);
assert.match(source, /distance < 8/);
assert.match(source, /放到这里/);
assert.match(source, /正在移动/);
assert.match(source, /Prompt 顺序已更新/);
assert.match(source, /const finishCall = async \(prompt: string, id: number, categoryId = activeTab\) =>/);
assert.match(source, /\[categoryId\]: \(prev\[categoryId\] \|\| \[\]\)\.map/);
assert.match(source, /categoryId,/);
assert.match(source, /const handleCall = async \(prompt: Prompt, categoryId = activeTab\) =>/);
assert.match(source, /setSelectedCategoryId\(categoryId\)/);
assert.match(source, /await finishCall\(fillPromptTemplate\(selectedPrompt\.prompt, templateValues\), selectedPrompt\.id, selectedCategoryId\)/);
assert.match(source, /const callLauncherPrompt = async \(prompt: Prompt, categoryId: string\) => \{\n\s+await handleCall\(prompt, categoryId\);/);
assert.match(source, /<Send className="w-3\.5 h-3\.5" \/>调用/);
assert.match(source, /webkit\.messageHandlers\.usePrompt\.postMessage/);
assert.doesNotMatch(source, /已调用 \$\{provider\} · \$\{model\}/);
assert.doesNotMatch(source, /生成并复制/);
