import assert from 'node:assert/strict';
import fs from 'node:fs';

const source = fs.readFileSync(new URL('./App.tsx', import.meta.url), 'utf8');

assert.match(source, /import appIconUrl from '..\/..\/tools\/prompt-manager-mac\/Assets\/PromptManager\.svg';/);
assert.match(source, /<img src=\{appIconUrl\}/);
assert.match(source, />Prompt Manager<\/div>/);
assert.doesNotMatch(source, />Prompt 管理器<\/div>/);
assert.match(source, /const \[activeTab, setActiveTab\] = useState<string>\('media'\);/);
assert.match(source, /\{ id: 'media',\s+label: '自媒体', icon: Megaphone, visible: true \}/);
assert.match(source, /\{ id: 'knowledge', label: '知识库', icon: Folder, visible: true \}/);
assert.doesNotMatch(source, /\{ id: 'coding'/);
assert.doesNotMatch(source, /\{ id: 'pm'/);
assert.match(source, /title: "短视频选题"/);
assert.match(source, /title: "知识库整理"/);
assert.doesNotMatch(source, /代码重构助手/);
assert.doesNotMatch(source, /Bug 调试专家/);
assert.match(source, /const \[aiRewriteInput, setAiRewriteInput\] = useState\(''\);/);
assert.match(source, /const aiRewriteAbortRef = useRef<AbortController \| null>\(null\);/);
assert.match(source, /const aiRewriteRunRef = useRef\(0\);/);
assert.match(source, /type AIProviderConfig = \{ model: string; apiKey: string; baseUrl: string \};/);
assert.match(source, /providerConfigs\?: Record<string, AIProviderConfig>;/);
assert.match(source, /const \[providerConfigs, setProviderConfigs\] = useState<Record<string, AIProviderConfig>>/);
assert.match(source, /const currentProviderConfig = providerConfigs\[provider\]/);
assert.match(source, /const configuredProviders = PROVIDERS\.filter/);
assert.match(source, /setProviderConfigs\(prev =>/);
assert.match(source, /configuredProviders\.map/);
assert.doesNotMatch(source, />调用模型</);
assert.match(source, /placeholder: 'deepseek-v4-pro'/);
assert.match(source, /import \{ aiCompletionEndpoint, buildAIRequestConfig, parseAICompletionText, resolveAIRequestProvider \} from '\.\/aiProviderRequest\.js';/);
assert.match(source, /const modelForProvider = \(provider: string, model: string\) =>/);
assert.match(source, /if \(provider === 'deepseek' && compact === 'deepseek-4\.0pro'\) return 'deepseek-v4-pro';/);
assert.match(source, /<select[\s\S]*value=\{activeCallProvider\}/);
assert.doesNotMatch(source, /\{item\.label\} · \{config\.model \|\| item\.placeholder\}/);
assert.match(source, /<option key=\{item\.id\} value=\{item\.id\}>\n\s+\{config\.model \|\| item\.placeholder\}\n\s+<\/option>/);
assert.match(source, /const rewriteTemplateWithAI = async \(\) =>/);
assert.match(source, /resolveAIRequestProvider\(\{/);
assert.match(source, /aiCompletionEndpoint\(requestProvider, activeCallConfig\.baseUrl\)/);
assert.match(source, /const requestChatCompletion = async /);
assert.match(source, /const createAbortError = \(\) =>/);
assert.match(source, /const isAbortError = \(error: unknown\) =>/);
assert.match(source, /messageHandlers\?\.aiChatCompletion/);
assert.match(source, /messageHandlers\?\.cancelAIChatCompletion/);
assert.match(source, /signal\?: AbortSignal/);
assert.match(source, /signal,\n\s+\}\)/);
assert.match(source, /cancelHandler\.postMessage\(\{ requestId \}\)/);
assert.match(source, /signal\?\.addEventListener\('abort', onAbort, \{ once: true \}\)/);
assert.match(source, /body: JSON\.stringify\(requestConfig\.body\),\n\s+signal,/);
assert.match(source, /prompt-manager-ai-result/);
assert.match(source, /AI 改写失败：\$\{formatAIErrorMessage\(error\)\}/);
assert.match(source, /const formatImportErrorMessage = \(error: unknown\) =>/);
assert.match(source, /showToast\(`导入失败：\$\{formatImportErrorMessage\(error\)\}`\)/);
assert.match(source, /import \{ buildAIRewritePayload \} from '\.\/aiRewritePayload\.js';/);
assert.match(source, /import \{ completeAIRewriteValues, extractAIRewriteValues, hasFilledAIRewriteValues \} from '\.\/aiRewriteResult\.js';/);
assert.match(source, /max_tokens\?: number;/);
assert.match(source, /buildAIRequestConfig\(\{ provider, apiKey, baseUrl, body \}\)/);
assert.match(source, /requestChatCompletion\(requestProvider, endpoint, activeCallConfig\.apiKey, activeCallConfig\.baseUrl, buildAIRewritePayload\(\{/);
assert.match(source, /const cancelAIRewrite = \(\) =>/);
assert.match(source, /aiRewriteAbortRef\.current\?\.abort\(\);/);
assert.match(source, /const updateCallPromptOpen = \(open: boolean\) =>/);
assert.match(source, /if \(!open && aiRewriting\) \{/);
assert.match(source, /const rewriteAbortController = new AbortController\(\);/);
assert.match(source, /aiRewriteRunRef\.current \+= 1;/);
assert.match(source, /rewriteAbortController\.signal/);
assert.match(source, /if \(rewriteAbortController\.signal\.aborted \|\| aiRewriteRunRef\.current !== rewriteRunId\) return;/);
assert.match(source, /if \(isAbortError\(error\)\) \{/);
assert.match(source, /parseAICompletionText\(requestProvider, data\)/);
assert.match(source, /template,\n\s+fields,\n\s+brief,/);
assert.match(source, /extractAIRewriteValues\(String\(content\), fields\)/);
assert.match(source, /completeAIRewriteValues\(\{\n\s+values: extractedValues,\n\s+fields,\n\s+brief,\n\s+title: selectedPrompt\.title,\n\s+template,\n\s+\}\)/);
assert.match(source, /hasFilledAIRewriteValues\(nextValues\)/);
assert.match(source, /const filledValues = Object\.fromEntries/);
assert.match(source, /setTemplateValues\(prev => \(\{ \.\.\.prev, \.\.\.filledValues \}\)\)/);
assert.match(source, /const \[rewriteHistory, setRewriteHistory\] = useState<Record<string, string>\[\]>\(\[\]\);/);
assert.match(source, /const \[rewriteHistoryIndex, setRewriteHistoryIndex\] = useState\(-1\);/);
assert.match(source, /lastRewriteValues\?: Record<string, Record<string, string>>;/);
assert.match(source, /launchAtLogin\?: boolean;/);
assert.match(source, /const \[launchAtLogin, setLaunchAtLogin\] = useState\(Boolean\(storedState\.launchAtLogin\)\);/);
assert.match(source, /const requestNativeLaunchAtLogin = \(enabled: boolean\) => new Promise<boolean>/);
assert.match(source, /messageHandlers\?\.launchAtLogin/);
assert.match(source, /prompt-manager-launch-at-login-result/);
assert.match(source, /const requestNativeUsePrompt = \(payload: Record<string, unknown>\) => new Promise<boolean>/);
assert.match(source, /messageHandlers\?\.usePrompt/);
assert.match(source, /prompt-manager-use-prompt-result/);
assert.match(source, /const requestId = `use-prompt-\$\{Date\.now\(\)\}-\$\{Math\.random\(\)\.toString\(36\)\.slice\(2\)\}`;/);
assert.match(source, /handler\.postMessage\(\{ \.\.\.payload, requestId \}\);/);
assert.match(source, /await requestNativeUsePrompt\(\{/);
assert.match(source, /showToast\('Prompt 已调用'\)/);
assert.match(source, /开机启动/);
assert.match(source, /const \[lastRewriteValues, setLastRewriteValues\] = useState<Record<string, Record<string, string>>>/);
assert.match(source, /const promptHistoryKey = \(prompt: Prompt, categoryId: string\) => `\$\{categoryId\}:\$\{prompt\.id\}`;/);
assert.match(source, /lastRewriteValues,/);
assert.match(source, /const \[selectedCategoryId, setSelectedCategoryId\] = useState\(activeTab\);/);
assert.match(source, /const nextHistory = \[\.\.\.baseHistory, filledValues\];/);
assert.match(source, /setTemplateValues\(prev => \(\{ \.\.\.prev, \.\.\.rewriteHistory\[nextIndex\] \}\)\)/);
assert.match(source, /setLastRewriteValues\(prev => \(\{ \.\.\.prev, \[promptHistoryKey\(selectedPrompt, selectedCategoryId\)\]: filledValues \}\)\)/);
assert.match(source, /const lastValues = selectedPrompt \? lastRewriteValues\[promptHistoryKey\(selectedPrompt, selectedCategoryId\)\] : undefined;/);
assert.match(source, /setTemplateValues\(prev => \(\{ \.\.\.prev, \.\.\.lastValues \}\)\)/);
assert.match(source, />AI改写</);
assert.match(source, /placeholder="输入几个关键词或几句话，AI 会改写成下面字段"/);
assert.match(source, /const templateFieldPlaceholder = \(field: string\) => \{/);
assert.match(source, /if \(normalized === '账号模式'\) return '个人号或医生号';/);
assert.doesNotMatch(source, /placeholder=\{`填写\$\{field\}`\}/);
assert.match(source, /top-8 z-\[60\]/);
assert.doesNotMatch(source, /bottom-8 z-\[60\]/);
assert.match(source, /w-\[560px\] max-w-\[92vw\] max-h-\[calc\(100vh-48px\)\] overflow-hidden flex flex-col rounded-3xl border/);
assert.match(source, /px-6 py-5 space-y-4 flex-1 min-h-0 overflow-y-auto/);
assert.match(source, /flex flex-col items-end gap-1\.5 px-6 pt-4 pb-3 border-t/);
assert.doesNotMatch(source, /flex flex-col items-end gap-1\.5 px-6 pt-4 pb-\[6px\] border-t/);
assert.match(source, /minWidth: 148/);
assert.match(source, /whiteSpace: 'nowrap'/);
assert.match(source, /flexShrink: 0/);
assert.match(source, /aiRewriting\s*\?\s*<span>改写中\.\.\.<\/span>/);
assert.match(source, /<span>AI填入字段<\/span>/);
assert.match(source, /const undoLastCall = \(\) =>/);
assert.match(source, /showToast\('已恢复上一次 AI 改写'\)/);
assert.doesNotMatch(source, /messageHandlers\?\.undoPrompt/);
assert.match(source, /上一次调用/);
assert.match(source, /data-prompt-card-id=\{prompt\.id\}/);
assert.match(source, /onPointerDown=\{\(event\) => handlePromptPointerDown\(event, prompt\.id\)\}/);
assert.match(source, /onPointerMove=\{handlePromptPointerMove\}/);
assert.match(source, /data-no-prompt-drag/);
assert.match(source, /promptDragActive/);
assert.match(source, /promptDragOffset/);
assert.match(source, /document\.body\.style\.userSelect = 'none'/);
assert.match(source, /document\.elementsFromPoint/);
assert.match(source, /translate3d\(\$\{promptDragOffset\.x\}px, \$\{promptDragOffset\.y\}px, 0\) scale\(1\.02\)/);
assert.match(source, /transition: isDraggingPrompt \? 'box-shadow 120ms ease, opacity 120ms ease' : undefined/);
assert.match(source, /willChange: isDraggingPrompt \? 'transform' : undefined/);
assert.match(source, /pointerEvents: isDraggingPrompt \? 'none' : undefined/);
assert.match(source, /distance < 8/);
assert.match(source, /放到这里/);
assert.match(source, /正在移动/);
assert.match(source, /Prompt 顺序已更新/);
assert.match(source, /const sourceCategoryId = Object\.keys\(next\)\.find/);
assert.match(source, /const sourceIndex = sourceCategoryId \? \(next\[sourceCategoryId\] \|\| \[\]\)\.findIndex/);
assert.match(source, /if \(sourceCategoryId === formCategory && sourceIndex >= 0\) \{/);
assert.match(source, /targetList\.splice\(sourceIndex, 0, updated\);/);
assert.match(source, /const \[importConflictOpen, setImportConflictOpen\] = useState\(false\);/);
assert.match(source, /const \[pendingImportRows, setPendingImportRows\] = useState<ImportedPrompt\[\]>\(\[\]\);/);
assert.match(source, /const applyImportedRows = \(importedRows: ImportedPrompt\[\], duplicateStrategy/);
assert.match(source, /readXlsxFile\(file,\s*\{\s*trim:\s*false\s*\}\)/);
assert.match(source, /const duplicateCount = countImportedPromptConflicts\(\{ categories, prompts, rows: importedRows \}\);/);
assert.match(source, /mergeImportedPromptRows\(\{ categories, prompts, rows: importedRows, duplicateStrategy \}\)/);
assert.match(source, />覆盖已有</);
assert.match(source, />跳过重复</);
assert.match(source, />另存为副本</);
assert.match(source, /const finishCall = async \(prompt: string, id: number, categoryId = activeTab, mode: CallMode = 'reuse'\) =>/);
assert.match(source, /const CALL_DEDUP_WINDOW_MS = \d+;/);
assert.match(source, /const lastCallActionRef = useRef<\{ key: string; time: number \} \| null>\(null\);/);
assert.match(source, /if \(lastCallActionRef\.current && lastCallActionRef\.current\.key === actionKey && now - lastCallActionRef\.current\.time < CALL_DEDUP_WINDOW_MS\) \{/);
assert.match(source, /lastCallActionRef\.current = \{ key: actionKey, time: now \};/);
assert.match(source, /const markPromptFeedback = \(\) => \{/);
assert.match(source, /const markPromptUsed = \(\) => \{/);
assert.match(source, /markPromptFeedback\(\);\n\s+showToast\('正在调用 Prompt'\);/);
assert.match(source, /markPromptUsed\(\);\n\s+showToast\('Prompt 已调用'\);/);
assert.match(source, /\[categoryId\]: \(prev\[categoryId\] \|\| \[\]\)\.map/);
assert.match(source, /categoryId,/);
assert.match(source, /const handleCall = async \(prompt: Prompt, categoryId = activeTab\) =>/);
assert.match(source, /setSelectedCategoryId\(categoryId\)/);
assert.match(source, /if \(mode === 'reuse'\) \{\n\s+await finishCall\(template, prompt\.id, categoryId, mode\);\n\s+return;\n\s+\}/);
assert.match(source, /const called = await finishCall\(fillManualTemplate\(template, templateValues\), selectedPrompt\.id, selectedCategoryId, selectedCallMode\);/);
assert.match(source, /if \(!called\) return;/);
assert.match(source, /const callLauncherPrompt = async \(prompt: Prompt, categoryId: string\) => \{\n\s+await handleCall\(prompt, categoryId\);/);
assert.match(source, />复用/);
assert.match(source, />定制/);
assert.match(source, /const toggleReusePromptDraft = \(\) => \{/);
assert.match(source, /setFormReusePrompt\(''\);/);
assert.match(source, /const toggleCustomPromptDraft = \(\) => \{/);
assert.match(source, /setFormCustomPrompt\(''\);/);
assert.match(source, /\{formCustomPrompt\.trim\(\) \? '禁用' : '启用'\}/);
assert.match(source, /borderColor: formCustomPrompt\.trim\(\) \? '#dbe7ff' : '#e2e8f0'/);
assert.match(source, /background: formCustomPrompt\.trim\(\) \? '#f8fbff' : '#fff'/);
assert.match(source, /删除分类“\$\{category\?\.label \|\| id\}”会同时删除其中 \$\{promptCount\} 个 Prompt，且无法恢复。确定继续吗？/);
assert.match(source, /if \(!ok\) return;\n\s+setCategories\(prev => prev\.filter\(c => c\.id !== id\)\);/);
assert.doesNotMatch(source, /请围绕「\{\{主题\}\}」/);
assert.doesNotMatch(source, /请读取上一步输出 \{\{上一步文件名\}\}/);
assert.match(source, /请围绕 \{\{主题\}\} 完成/);
assert.match(source, /handler\.postMessage\(\{ \.\.\.payload, requestId \}\);/);
assert.doesNotMatch(source, /已调用 \$\{provider\} · \$\{model\}/);
assert.doesNotMatch(source, /生成并复制/);
