import assert from 'node:assert/strict';
import fs from 'node:fs';

const source = fs.readFileSync(new URL('./Sources/main.swift', import.meta.url), 'utf8');

assert.match(source, /private var lastTargetApp: NSRunningApplication\?/);
assert.match(source, /installActivationObserver\(\)/);
assert.match(source, /requestAccessibilityPermission\(\)/);
assert.match(source, /setupMainMenu\(\)/);
assert.match(source, /NSApp\.setActivationPolicy\(\.accessory\)/);
assert.doesNotMatch(source, /NSApp\.setActivationPolicy\(\.regular\)/);
assert.match(source, /window\.title = "Prompt Manager"/);
assert.match(source, /window\.collectionBehavior = \[\.moveToActiveSpace, \.fullScreenAuxiliary\]/);
assert.doesNotMatch(source, /\.canJoinAllSpaces, \.moveToActiveSpace/);
assert.match(source, /NSImage\(named: "PromptManagerMenuBar"\)/);
assert.match(source, /menuBarImage\.size = NSSize\(width: 18, height: 18\)/);
assert.match(source, /item\.button\?\.image = menuBarImage/);
assert.match(source, /NSStatusBar\.system\.statusItem\(withLength: NSStatusItem\.squareLength\)/);
assert.match(source, /item\.button\?\.title = ""/);
assert.match(source, /item\.button\?\.imagePosition = \.imageOnly/);
assert.doesNotMatch(source, /item\.button\?\.title = "Prompt Manager"/);
assert.match(source, /NSMenuItem\(title: "Open Prompt Manager"/);
assert.doesNotMatch(source, /打开 Prompt 管理器/);
assert.match(source, /let editMenu = NSMenu\(title: "Edit"\)/);
assert.match(source, /NSMenuItem\(title: "Paste", action: #selector\(NSText\.paste\(_:\)\), keyEquivalent: "v"\)/);
assert.match(source, /final class PromptEditingWebView: WKWebView/);
assert.match(source, /override func performKeyEquivalent\(with event: NSEvent\) -> Bool/);
assert.match(source, /case kVK_ANSI_V:\n\s+action = #selector\(NSText\.paste\(_:\)\)/);
assert.match(source, /self\.webView = PromptEditingWebView\(frame: \.zero, configuration: configuration\)/);
assert.match(source, /sourceAppForPromptWindow = currentTargetApp\(\)/);
assert.match(source, /let targetApp = sourceApp \?\? currentTargetApp\(\)/);
assert.match(source, /private let usePromptDedupInterval: TimeInterval = 0\.9/);
assert.match(source, /private var lastUsePromptAction: \(key: String, time: Date\)\?/);
assert.match(source, /let actionKey = "\\\(targetApp\.processIdentifier\):\\\(item\.id\):\\\(item\.prompt\.hashValue\)"/);
assert.match(source, /if let lastUsePromptAction,\n\s+lastUsePromptAction\.key == actionKey,\n\s+Date\(\)\.timeIntervalSince\(lastUsePromptAction\.time\) < usePromptDedupInterval \{/);
assert.match(source, /pastePromptIntoTargetApp\(targetApp, attempt: 0, shortcut: \.paste, requestId: item\.requestId, completion: completion\)/);
assert.match(source, /private func pastePromptIntoTargetApp\(_ targetApp: NSRunningApplication, attempt: Int, shortcut: TargetShortcut, requestId: String\?, completion: \(\(Bool, String\) -> Void\)\? = nil\)/);
assert.match(source, /private let focusSettleDelay: TimeInterval = 0\.18/);
assert.match(source, /private let keyboardPasteSettleDelay: TimeInterval = 0\.25/);
assert.match(source, /let settleDelay = shouldUseKeyboardPaste\(for: targetApp\) \? keyboardPasteSettleDelay : focusSettleDelay/);
assert.match(source, /DispatchQueue\.main\.asyncAfter\(deadline: \.now\(\) \+ settleDelay\)/);
assert.match(source, /self\.pastePromptIntoTargetApp\(targetApp, attempt: attempt \+ 1, shortcut: shortcut, requestId: requestId, completion: completion\)/);
assert.match(source, /private func insertPrompt\(_ prompt: String, intoFocusedElementOf app: NSRunningApplication\) -> Bool/);
assert.match(source, /private func insertPrompt\(_ prompt: String, into focusedElement: AXUIElement\) -> Bool/);
assert.match(source, /private func shouldUseKeyboardPaste\(for app: NSRunningApplication\) -> Bool/);
assert.match(source, /"com\.openai\.codex"/);
assert.match(source, /"com\.apple\.Terminal"/);
assert.match(source, /"com\.googlecode\.iterm2"/);
assert.match(source, /"com\.microsoft\.VSCode"/);
assert.match(source, /"dev\.warp\.Warp-Stable"/);
assert.match(source, /if !shouldUseKeyboardPaste\(for: targetApp\),\n\s+insertPrompt\(pendingPromptText, intoFocusedElementOf: targetApp\) \{/);
assert.match(source, /notifyUsePromptResult\(requestId: requestId, ok: true, message: "Prompt 已调用"\)/);
assert.match(source, /notifyUsePromptResult\(requestId: requestId, ok: false, message: "调用失败：无法发送粘贴快捷键"\)/);
assert.match(source, /AXUIElementSetAttributeValue\(focusedElement, kAXValueAttribute as CFString, nextValue as CFTypeRef\)/);
assert.match(source, /if NSWorkspace\.shared\.frontmostApplication\?\.processIdentifier != targetApp\.processIdentifier \{/);
assert.match(source, /DispatchQueue\.main\.asyncAfter\(deadline: \.now\(\) \+ 0\.12\)/);
assert.match(source, /private func postPasteShortcut\(\) -> Bool/);
assert.match(source, /private enum TargetShortcut/);
assert.match(source, /keyDown\.post\(tap: \.cghidEventTap\)/);
assert.match(source, /RegisterEventHotKey\(\n\s+keyCode,\n\s+modifiers,\n\s+hotKeyID,\n\s+GetApplicationEventTarget\(\),\n\s+UInt32\(kEventHotKeyExclusive\),/);
assert.match(source, /webView\.configuration\.userContentController\.add\(self, name: "importFile"\)/);
assert.match(source, /webView\.configuration\.userContentController\.add\(self, name: "aiChatCompletion"\)/);
assert.match(source, /webView\.configuration\.userContentController\.add\(self, name: "cancelAIChatCompletion"\)/);
assert.match(source, /webView\.configuration\.userContentController\.removeScriptMessageHandler\(forName: "aiChatCompletion"\)/);
assert.match(source, /webView\.configuration\.userContentController\.removeScriptMessageHandler\(forName: "cancelAIChatCompletion"\)/);
assert.match(source, /if message\.name == "aiChatCompletion" \{/);
assert.match(source, /if message\.name == "cancelAIChatCompletion" \{/);
assert.match(source, /private var activeAIChatCompletionTasks: \[String: URLSessionDataTask\] = \[:\]/);
assert.match(source, /private func performAIChatCompletion\(_ body: \[String: Any\]\)/);
assert.match(source, /private func cancelAIChatCompletion\(_ body: \[String: Any\]\)/);
assert.match(source, /let headers = body\["headers"\] as\? \[String: String\] \?\? \[:\]/);
assert.match(source, /headers\.forEach \{ field, value in/);
assert.match(source, /let task = URLSession\.shared\.dataTask\(with: request\)/);
assert.match(source, /activeAIChatCompletionTasks\[requestId\] = task/);
assert.match(source, /task\.cancel\(\)/);
assert.match(source, /NSLog\("PromptManager AI request started: requestId=%@ endpoint=%@", requestId, endpoint\)/);
assert.match(source, /NSLog\("PromptManager AI request cancelled: requestId=%@", requestId\)/);
assert.match(source, /prompt-manager-ai-result/);
assert.match(source, /let requestId = body\["requestId"\] as\? String \?\? ""/);
assert.match(source, /private func notifyUsePromptResult\(requestId: String, ok: Bool, message: String\)/);
assert.match(source, /prompt-manager-use-prompt-result/);
assert.match(source, /webView\.configuration\.userContentController\.add\(self, name: "launchAtLogin"\)/);
assert.match(source, /webView\.configuration\.userContentController\.removeScriptMessageHandler\(forName: "launchAtLogin"\)/);
assert.match(source, /if message\.name == "launchAtLogin" \{/);
assert.match(source, /enum LaunchAtLoginController/);
assert.match(source, /appendingPathComponent\("Library\/LaunchAgents", isDirectory: true\)/);
assert.match(source, /runLaunchctl\(\["bootstrap", guiDomain, plistURL\.path\]\)/);
assert.match(source, /prompt-manager-launch-at-login-result/);
assert.match(source, /runJavaScriptConfirmPanelWithMessage/);
assert.match(source, /func jsString\(_ string: String\) -> String \{\n\s+if let data = try\? JSONEncoder\(\)\.encode\(string\)/);
assert.doesNotMatch(source, /JSONSerialization\.data\(withJSONObject: string/);
